# SwiftLint Configuration for Thea
# Focus on critical issues, not stylistic preferences

excluded:
  - .build
  - DerivedData
  - Packages
  - Tests
  - UITests
  - "*.generated.swift"

disabled_rules:
  - trailing_whitespace
  - line_length
  - file_length
  - type_body_length
  - function_body_length
  - cyclomatic_complexity
  - nesting
  - identifier_name
  - type_name
  - large_tuple
  - todo
  - trailing_comma
  - multiple_closures_with_trailing_closure
  - for_where
  - unused_optional_binding
  - first_where
  - comment_spacing

opt_in_rules:
  - empty_count
  - closure_spacing
  - overridden_super_call
  - redundant_nil_coalescing
  - sorted_first_last

# Downgrade force unwrapping to warning (common in URL initialization)
force_cast: warning
force_try: warning
force_unwrapping: warning
implicitly_unwrapped_optional: warning
