# SwiftLint Configuration for Thea
# This helps catch issues before building

# Paths to include/exclude
included:
  - Shared
  - iOS
  - macOS

excluded:
  - Pods
  - DerivedData
  - Build
  - .build

# Enabled Rules
opt_in_rules:
  - explicit_init
  - explicit_type_interface
  - fatal_error_message
  - missing_docs
  - overridden_super_call
  - private_outlet
  - prohibited_super_call
  - required_deinit
  - strict_fileprivate
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unused_declaration
  - unused_import

# Disabled Rules (only when necessary)
disabled_rules:
  - line_length  # Can be too strict
  - type_body_length  # Actors can be long

# Rule Configurations
identifier_name:
  min_length: 1  # Allow single-letter variables
  max_length: 60

type_name:
  min_length: 2
  max_length: 60

function_body_length:
  warning: 100
  error: 200

file_length:
  warning: 500
  error: 1000

cyclomatic_complexity:
  warning: 15
  error: 25

# Custom Rules
custom_rules:
  # Catch common typos
  deprecated_cgwindow:
    name: "Deprecated CGWindow API"
    regex: "CGWindowListCreateImage"
    match_kinds: identifier
    message: "Use ScreenCaptureKit instead of deprecated CGWindowListCreateImage"
    severity: warning
    
  # Warn about force unwrapping
  force_unwrap:
    name: "Force Unwrapping"
    regex: "\\!(?![=])"
    message: "Avoid force unwrapping - use guard let or if let"
    severity: warning
    
  # Warn about empty catch blocks
  empty_catch:
    name: "Empty Catch"
    regex: "catch\\s*\\{\\s*\\}"
    message: "Avoid empty catch blocks - at least log the error"
    severity: warning

# Reporter
reporter: "xcode"  # Use Xcode-compatible format
