// MarkdownWriter.swift
// Markdown output writer for audit findings (PR summaries)

import Foundation

/// Writes audit findings to Markdown format for PR summaries
struct MarkdownWriter {
    /// Write findings and optional policy result to a Markdown file
    static func write(findings: [Finding], policyResult: PolicyEvaluationResult?, to path: String) throws {
        var md = """
        # thea-audit Security Report

        Generated: \(ISO8601DateFormatter().string(from: Date()))


        """

        // Summary section
        let criticalCount = findings.filter { $0.severity == .critical }.count
        let highCount = findings.filter { $0.severity == .high }.count
        let mediumCount = findings.filter { $0.severity == .medium }.count
        let lowCount = findings.filter { $0.severity == .low }.count

        md += """
        ## Summary

        | Severity | Count |
        |----------|-------|
        | \(Severity.critical.emoji) Critical | \(criticalCount) |
        | \(Severity.high.emoji) High | \(highCount) |
        | \(Severity.medium.emoji) Medium | \(mediumCount) |
        | \(Severity.low.emoji) Low | \(lowCount) |
        | **Total** | **\(findings.count)** |


        """

        // Policy compliance section
        if let result = policyResult {
            md += """
            ## Policy Compliance

            **Status:** \(result.compliant ? "PASS" : "FAIL")

            """

            if !result.violations.isEmpty {
                md += """
                ### Violations

                """
                for violation in result.violations {
                    md += "- \(violation)\n"
                }
                md += "\n"
            }
        }

        // Findings by severity
        if criticalCount > 0 {
            md += """
            ## Critical Findings

            """
            md += formatFindings(findings.filter { $0.severity == .critical })
        }

        if highCount > 0 {
            md += """
            ## High Severity Findings

            """
            md += formatFindings(findings.filter { $0.severity == .high })
        }

        if mediumCount > 0 {
            md += """
            ## Medium Severity Findings

            """
            md += formatFindings(findings.filter { $0.severity == .medium })
        }

        if lowCount > 0 {
            md += """
            ## Low Severity Findings

            <details>
            <summary>Click to expand \(lowCount) low severity findings</summary>

            """
            md += formatFindings(findings.filter { $0.severity == .low })
            md += "</details>\n\n"
        }

        // Footer
        md += """
        ---

        *Generated by thea-audit v1.0.0 - Part of AgentSec Strict Mode*
        """

        // Write to file
        try md.write(toFile: path, atomically: true, encoding: .utf8)
    }

    /// Format a list of findings as markdown
    private static func formatFindings(_ findings: [Finding]) -> String {
        var md = ""

        for finding in findings {
            md += """
            ### \(finding.title)

            - **Rule:** `\(finding.ruleID)`
            - **File:** `\(finding.location)`
            - **Category:** \(finding.category.rawValue)

            """

            if let cwe = finding.cweID {
                md += "- **CWE:** \(cwe)\n"
            }

            md += """

            \(finding.description)

            """

            if let evidence = finding.evidence {
                md += """

                **Evidence:**
                ```
                \(evidence)
                ```

                """
            }

            md += """

            **Recommendation:** \(finding.recommendation)

            ---


            """
        }

        return md
    }
}
