# SwiftLint Configuration for Thea
# Version: 2.0.0 - Enhanced QA Configuration
# Last Updated: January 16, 2026

# ============================================
# INCLUDED PATHS
# ============================================
included:
  - Shared
  - Platforms
  - iOS
  - macOS
  - watchOS
  - tvOS
  - iPadOS
  - Tests

# ============================================
# EXCLUDED PATHS
# ============================================
excluded:
  - .build
  - build
  - .swiftpm
  - Pods
  - Carthage
  - DerivedData
  - .backup*
  - Package.swift
  - "**/.build"

# ============================================
# DISABLED RULES (Development Phase)
# ============================================
# These rules are disabled during active development
# Re-enable before production release
disabled_rules:
  - line_length               # Custom line length configured below
  - trailing_whitespace       # Auto-fixed by Xcode
  - todo                      # TODOs are intentional during development
  - multiple_closures_with_trailing_closure  # Common in SwiftUI
  - opening_brace             # Conflicts with some SwiftUI patterns
  - vertical_whitespace       # Allow extra blank lines for readability

# ============================================
# OPT-IN RULES (Stricter Quality)
# ============================================
opt_in_rules:
  # Array and Collection
  - array_init
  - collection_alignment
  - empty_collection_literal
  - empty_count
  - empty_string
  - first_where
  - last_where
  - sorted_first_last

  # Closures
  - closure_end_indentation
  - closure_spacing
  - trailing_closure
  - unneeded_parentheses_in_closure_argument

  # Code Style
  - attributes
  - implicit_return
  - literal_expression_end_indentation
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - number_separator
  - operator_usage_whitespace
  - sorted_imports
  - switch_case_on_newline
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces

  # Contains/Filter optimization
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison

  # Enum
  - enum_case_associated_values_count
  - optional_enum_case_matching
  - raw_value_for_camel_cased_codable_enum

  # Error Handling
  - fatal_error_message
  - untyped_error_in_catch

  # Extensions
  - extension_access_modifier
  - override_in_extension

  # File organization
  - file_name
  - file_name_no_space
  - type_contents_order

  # Force unwrapping
  - force_unwrapping

  # Functions
  - convenience_type
  - explicit_init
  - joined_default_parameter
  - unavailable_function

  # Legacy
  - legacy_multiple
  - legacy_random

  # Map/Reduce/Filter
  - flatmap_over_map_reduce
  - reduce_into

  # Nil handling
  - redundant_nil_coalescing

  # Operators
  - identical_operands
  - static_operator
  - yoda_condition

  # Self
  - lower_acl_than_parent
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init

  # Super
  - overridden_super_call
  - prohibited_super_call

  # Tests
  - nimble_operator
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - single_test_class
  - xct_specific_matcher

  # Toggles
  - toggle_bool

  # Types
  - redundant_type_annotation

  # Variables
  - fallthrough
  - pattern_matching_keywords
  - unowned_variable_capture

# ============================================
# ANALYZER RULES (Requires Compilation)
# ============================================
analyzer_rules:
  - explicit_self
  - unused_declaration
  - unused_import

# ============================================
# RULE CONFIGURATIONS
# ============================================

# File Length
file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

# Type Body Length
type_body_length:
  warning: 300
  error: 500

# Function Body Length
function_body_length:
  warning: 50
  error: 100

# Function Parameter Count
function_parameter_count:
  warning: 6
  error: 8
  ignores_default_parameters: true

# Cyclomatic Complexity
cyclomatic_complexity:
  warning: 15
  error: 25
  ignores_case_statements: true

# Nesting
nesting:
  type_level:
    warning: 3
    error: 5
  function_level:
    warning: 3
    error: 5

# Identifier Name
identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - db
    - ai
    - ok
    - to
    - x
    - y
    - z
    - i
    - j
    - k
    - n
    - a
    - b
    - r
    - g
    - UI
    - ID
    - AI
    - OS

# Large Tuple
large_tuple:
  warning: 4
  error: 6

# Type Name
type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 50
    error: 60
  excluded:
    - AI
    - ID
    - UI
    - OK
    - OS

# Line Length (custom)
line_length:
  warning: 150
  error: 200
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true

# Trailing Comma
trailing_comma:
  mandatory_comma: false

# Vertical Whitespace
vertical_whitespace:
  max_empty_lines: 2

# Warning Threshold
warning_threshold: 100

# ============================================
# CUSTOM RULES
# ============================================
custom_rules:
  # Ensure @MainActor for managers
  manager_main_actor:
    name: "Managers should use @MainActor"
    regex: 'final class \w+Manager[^:]*:'
    match_kinds:
      - identifier
    message: "Manager classes should use @MainActor for thread safety."
    severity: warning

  # Prevent print statements in production
  no_print_statements:
    name: "No Print Statements"
    regex: '\bprint\s*\('
    match_kinds:
      - identifier
    message: "Use os_log or Logger instead of print() for production code."
    severity: warning

  # Ensure async functions handle errors
  async_error_handling:
    name: "Async Error Handling"
    regex: 'Task\s*\{\s*(?!.*try)'
    message: "Task blocks should include try/catch for proper error handling."
    severity: warning

  # Prefer Task over DispatchQueue for concurrency
  prefer_task_over_dispatch:
    name: "Prefer Task over DispatchQueue"
    regex: 'DispatchQueue\.(main|global)'
    message: "Consider using Task and @MainActor instead of DispatchQueue for modern concurrency."
    severity: warning

  # Ensure UserDefaults keys are constants
  userdefaults_string_literal:
    name: "UserDefaults Key Constants"
    regex: 'UserDefaults\.standard\.(set|string|bool|integer|double|data|object)\(.*forKey:\s*"'
    message: "Use constants for UserDefaults keys to prevent typos."
    severity: warning

# ============================================
# REPORTER
# ============================================
reporter: "xcode"
