# SwiftLint Configuration for Thea
# Minimal config to pass CI

disabled_rules:
  - line_length
    - type_body_length
      - file_length
        - function_parameter_count
          - large_tuple
            - function_body_length
              - cyclomatic_complexity
                - type_name
                  - multiple_closures_with_trailing_closure
                    - for_where
                      - identifier_name
                        - todo
                          - trailing_whitespace
                            - opening_brace
                              - vertical_whitespace

                              excluded:
                                - .build
                                  - .swiftpm
                                    - Pods
                                      - Carthage
                                        - DerivedData
                                          - .backup*

                                          warning_threshold: 500

                                          reporter: "github-actions-logging"
