name: Thea
options:
  bundleIdPrefix: app.thea
  deploymentTarget:
    macOS: "14.0"
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top
  developmentLanguage: en
  indentWidth: 4
  tabWidth: 4
  usesTabs: false

settings:
  base:
    MARKETING_VERSION: "1.4.1"
    CURRENT_PROJECT_VERSION: "1.4.1"
    SWIFT_VERSION: "6.0"
    SWIFT_STRICT_CONCURRENCY: complete
    ENABLE_USER_SCRIPT_SANDBOXING: false
    CLANG_ENABLE_MODULES: true
    # Disable module interface emission (not needed for app targets)
    SWIFT_EMIT_MODULE_INTERFACE: false
    BUILD_LIBRARY_FOR_DISTRIBUTION: false
    # Signing - inherited by all targets
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: 6B66PM4JLK
    # Recommended settings from Xcode
    DEAD_CODE_STRIPPING: YES
    SWIFT_EMIT_LOC_STRINGS: YES

packages:
  OpenAI:
    url: https://github.com/MacPaw/OpenAI
    from: 0.2.0
  KeychainAccess:
    url: https://github.com/kishikawakatsumi/KeychainAccess
    from: 4.2.0
  MarkdownUI:
    url: https://github.com/gonzalezreal/swift-markdown-ui
    from: 2.0.0
  Highlightr:
    url: https://github.com/raspu/Highlightr
    from: 2.1.0

targets:
  # ============ macOS App ============
  Thea-macOS:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: Shared
        excludes:
          - "**/*iOS*"
          - "**/*watchOS*"
          - "**/*tvOS*"
          - "**/*.md"
      - path: macOS
      - path: Shared/Resources/Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: app.thea.macos
        PRODUCT_NAME: Thea
        PRODUCT_MODULE_NAME: TheaCore
        INFOPLIST_FILE: Shared/Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: macOS/Thea.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        COMBINE_HIDPI_IMAGES: true
        # Hardened runtime for macOS (recommended)
        ENABLE_HARDENED_RUNTIME: YES
      debug:
        ENABLE_HARDENED_RUNTIME: YES
      release:
        ENABLE_HARDENED_RUNTIME: YES
    dependencies:
      - package: OpenAI
      - package: KeychainAccess
      - package: MarkdownUI
      - package: Highlightr
    info:
      path: Shared/Resources/Info.plist
      properties:
        CFBundleDisplayName: Thea
        CFBundleName: Thea
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundlePackageType: APPL
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        LSMinimumSystemVersion: $(MACOSX_DEPLOYMENT_TARGET)
        NSHumanReadableCopyright: "Copyright © 2026 Thea. All rights reserved."
        NSMainStoryboardFile: ""
        NSPrincipalClass: NSApplication

  # ============ iOS App ============
  Thea-iOS:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Shared
        excludes:
          - "**/*macOS*"
          - "**/*watchOS*"
          - "**/*tvOS*"
          - "**/*.md"
          - "**/Terminal/**"
          - "**/ScreenCapture.swift"
          - "**/InputTrackingManager.swift"
          - "**/*AutomationEngine.swift"
          - "**/AppIntegration/**"
          - "**/TerminalService.swift"
          - "**/TerminalIntegration.swift"
          - "**/DisplayProfileManager.swift"
          - "**/DisplayService.swift"
          - "**/DisplayModels.swift"
          - "**/MLXModelManager.swift"
          - "**/ScreenshotPreview.swift"
          - "**/HandoffManager.swift"
          - "**/LocalModelsView.swift"
          - "**/LocalModelsSettingsView.swift"
          - "**/FolderAccessManager.swift"
      - path: iOS
      - path: Shared/Resources/Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: app.thea.ios
        PRODUCT_NAME: Thea
        PRODUCT_MODULE_NAME: TheaCore
        INFOPLIST_FILE: Shared/Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: iOS/Thea.entitlements
        TARGETED_DEVICE_FAMILY: "1,2"
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
        SUPPORTS_MACCATALYST: false
    dependencies:
      - package: OpenAI
      - package: KeychainAccess
      - package: MarkdownUI
      - package: Highlightr
    info:
      path: Shared/Resources/Info.plist
      properties:
        CFBundleDisplayName: Thea
        CFBundleName: Thea
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundlePackageType: APPL
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight

  # ============ Tests ============
  TheaTests:
    type: bundle.unit-test
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: Tests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: app.thea.tests
        INFOPLIST_FILE: Tests/Info.plist
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Thea.app/Contents/MacOS/Thea"
        BUNDLE_LOADER: "$(TEST_HOST)"
    dependencies:
      - target: Thea-macOS
      - package: OpenAI
      - package: KeychainAccess

schemes:
  Thea-macOS:
    build:
      targets:
        Thea-macOS: all
    run:
      config: Debug
      commandLineArguments:
        "-com.apple.CoreData.ConcurrencyDebug": true
    test:
      config: Debug
      gatherCoverageData: true
      targets:
        - TheaTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

  Thea-iOS:
    build:
      targets:
        Thea-iOS: all
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
