//
//  APIGenerator.swift
//  Thea
//
//  Created by Claude Code on 2026-01-20
//  Copyright © 2026. All rights reserved.
//

import Foundation

// MARK: - API Generator

/// Generates REST API client code from specifications
public actor APIGenerator {
    public static let shared = APIGenerator()

    // MARK: - State

    var generatedAPIs: [String: GeneratedAPI] = [:]
    var templates: [String: APITemplate] = [:]

    // MARK: - Initialization

    private init() {
        // Templates are initialized lazily
    }

    /// Initialize default templates - call before first use
    public func initialize() {
        loadDefaultTemplates()
    }

    // MARK: - API Generation

    /// Generate API client from specification
    public func generateAPI(from spec: APISpec) async throws -> GeneratedAPI {
        var code = """
        //
        //  \(spec.name)API.swift
        //  Generated by Thea API Builder
        //
        //  Created on \(ISO8601DateFormatter().string(from: Date()))
        //

        import Foundation

        // MARK: - \(spec.name) API Client

        """

        // Generate models
        for model in spec.models {
            code += generateModel(model)
        }

        // Generate API client
        code += generateAPIClient(for: spec)

        // Generate endpoints
        for endpoint in spec.endpoints {
            code += generateEndpoint(endpoint, apiName: spec.name)
        }

        // Close the class
        code += "}\n"

        let api = GeneratedAPI(
            id: UUID().uuidString,
            name: spec.name,
            spec: spec,
            generatedCode: code,
            generatedAt: Date()
        )

        generatedAPIs[api.id] = api
        return api
    }

    /// Generate API from OpenAPI/Swagger specification
    public func generateFromOpenAPI(_ openAPISpec: Data) async throws -> GeneratedAPI {
        let spec = try parseOpenAPISpec(openAPISpec)
        return try await generateAPI(from: spec)
    }

    /// Generate API from template
    public func generateFromTemplate(_ templateName: String, config: APITemplateConfig) async throws -> GeneratedAPI {
        guard let template = templates[templateName] else {
            throw APIGeneratorError.templateNotFound(templateName)
        }

        let spec = template.createSpec(with: config)
        return try await generateAPI(from: spec)
    }

    // MARK: - Template Access

    /// Get available templates
    public func getAvailableTemplates() -> [APITemplate] {
        Array(templates.values)
    }

    /// Get generated API by ID
    public func getGeneratedAPI(_ id: String) -> GeneratedAPI? {
        generatedAPIs[id]
    }
}

// MARK: - APIGenerator + OpenAPI Parsing

extension APIGenerator {
    // periphery:ignore - Reserved: parseOpenAPISpecData(_:) instance method reserved for future feature activation
    func parseOpenAPISpecData(_ data: Data) throws -> APISpec {
        try parseOpenAPISpec(data)
    }
}
