#!/usr/bin/env bash
# AZ3 setup.sh — Detect Thunderbolt Bridge IPs and verify connectivity
# Run this once before launch-az3.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG="$SCRIPT_DIR/config.env"

echo "=== AZ3 Setup ==="

# --- Detect Thunderbolt Bridge IPs ---
echo "[1/4] Detecting Thunderbolt Bridge IPs..."

# Parse bridge0 interface for the first inet address on this machine (MSM3U)
MSM3U_TB_IP=$(ifconfig bridge0 2>/dev/null | grep 'inet ' | awk '{print $2}' | head -1)
if [[ -z "$MSM3U_TB_IP" ]]; then
    echo "  WARNING: No bridge0 inet address found on this machine."
    echo "  Ensure Thunderbolt Bridge is connected and assigned a link-local IP (169.254.x.x)."
    MSM3U_TB_IP=""
else
    echo "  MSM3U Thunderbolt IP: $MSM3U_TB_IP"
fi

# Load existing config to get MBAM2_SSH_HOST
MBAM2_SSH_HOST="mbam2.local"
if [[ -f "$CONFIG" ]]; then
    # shellcheck disable=SC1090
    source "$CONFIG" 2>/dev/null || true
fi

# Query MBAM2 for its bridge0 IP over SSH
echo "[2/4] Querying MBAM2 Thunderbolt IP via SSH ($MBAM2_SSH_HOST)..."
MBAM2_TB_IP=$(ssh -o ConnectTimeout=10 -o BatchMode=yes "alexis@$MBAM2_SSH_HOST" \
    "ifconfig bridge0 2>/dev/null | grep 'inet ' | awk '{print \$2}' | head -1" 2>/dev/null || true)

if [[ -z "$MBAM2_TB_IP" ]]; then
    echo "  WARNING: Could not retrieve MBAM2 bridge0 IP. SSH may not be available or bridge0 not configured."
    MBAM2_TB_IP=""
else
    echo "  MBAM2 Thunderbolt IP: $MBAM2_TB_IP"
fi

# --- Write config.env ---
echo "[3/4] Writing config.env..."
cat > "$CONFIG" << ENVEOF
# AZ3 Cross-Mac Visual Test Configuration
# Generated by setup.sh — do not edit manually
MSM3U_TB_IP=$MSM3U_TB_IP
MBAM2_TB_IP=$MBAM2_TB_IP
MBAM2_SSH_HOST=$MBAM2_SSH_HOST
MBAM2_SCREENCAPTURE_PATH=/tmp/msm3u_frame.png
AZ3_RESULT_PORT=18790
AZ3_LOG_DIR=/tmp/az3-logs
ENVEOF
echo "  Written: $CONFIG"

# --- Verify SSH connectivity ---
echo "[4/4] Verifying SSH connectivity to MBAM2..."
if ssh -o ConnectTimeout=10 -o BatchMode=yes "alexis@$MBAM2_SSH_HOST" "echo OK" 2>/dev/null | grep -q "OK"; then
    echo "  SSH connectivity to $MBAM2_SSH_HOST: OK"
else
    echo "  WARNING: SSH to $MBAM2_SSH_HOST failed. Ensure:"
    echo "    - Remote Login is enabled on MBAM2 (System Settings → General → Sharing → Remote Login)"
    echo "    - SSH key auth is configured (ssh-copy-id alexis@$MBAM2_SSH_HOST)"
fi

# --- Create log directory ---
AZ3_LOG_DIR="/tmp/az3-logs"
mkdir -p "$AZ3_LOG_DIR"
echo ""
echo "=== AZ3 Setup Complete ==="
echo "  MSM3U_TB_IP : ${MSM3U_TB_IP:-<not detected>}"
echo "  MBAM2_TB_IP : ${MBAM2_TB_IP:-<not detected>}"
echo "  MBAM2 SSH   : alexis@$MBAM2_SSH_HOST"
echo "  Log dir     : $AZ3_LOG_DIR"
echo ""
echo "Next step: .claude/az3/launch-az3.sh"
