// AIFeaturesSettingsView.swift
// Thea
//
// Settings view for AI-powered dynamic features
// Exposes toggles for semantic classification, adaptive routing, AI analysis, etc.

import SwiftUI
import OSLog

private let logger = Logger(subsystem: "ai.thea.app", category: "AIFeaturesSettingsView")

// MARK: - AI Features Settings View

struct AIFeaturesSettingsView: View {
    // AI System Toggles
    @State private var useSemanticClassification = true
    @State private var useAdaptiveRouting = true
    @State private var useAICodeAnalysis = true
    @State private var useAIDynamicPrompts = true

    // AI Learning Settings
    @State private var enablePerformanceLearning = true
    @State private var learningDataRetentionDays: Double = 30

    // Cost & Quality Balance
    @State private var qualityVsCostBalance: Double = 0.7 // 0 = cost priority, 1 = quality priority

    // Advanced
    @State private var showAdvancedSettings = false
    @State private var minConfidenceForAI: Double = 0.7
    @State private var fallbackToKeywordMatching = true

    var body: some View {
        Form {
            overviewSection
            coreAIFeaturesSection
            intelligenceModesSection
            learningSettingsSection
            performanceBalanceSection

            if showAdvancedSettings {
                advancedSection
            }

            actionsSection
        }
        .formStyle(.grouped)
        #if os(macOS)
        .padding()
        #endif
        .onAppear {
            loadCurrentSettings()
        }
        .onChange(of: useSemanticClassification) { _, newValue in
            applySemanticClassification(newValue)
        }
        .onChange(of: useAdaptiveRouting) { _, newValue in
            applyAdaptiveRouting(newValue)
        }
        .onChange(of: useAICodeAnalysis) { _, newValue in
            applyAICodeAnalysis(newValue)
        }
        .onChange(of: useAIDynamicPrompts) { _, newValue in
            applyAIDynamicPrompts(newValue)
        }
    }

    // MARK: - Overview Section

    private var overviewSection: some View {
        Section {
            VStack(alignment: .leading, spacing: 12) {
                HStack {
                    Image(systemName: "sparkles")
                        .font(.title2)
                        .foregroundStyle(.purple)
                    Text("AI-Powered Intelligence")
                        .font(.headline)
                }

                Text("Enable AI-powered dynamic features that learn and adapt to improve performance over time. These replace static pattern-matching with semantic understanding.")
                    .font(.caption)
                    .foregroundStyle(.secondary)

                // Status summary
                HStack(spacing: 16) {
                    AIFeatureStatusBadge(
                        title: "Active",
                        count: activeFeatureCount,
                        total: 4,
                        color: .green
                    )

                    AIFeatureStatusBadge(
                        title: "Learning",
                        count: enablePerformanceLearning ? 1 : 0,
                        total: 1,
                        color: .blue
                    )
                }
                .padding(.top, 4)
            }
            .padding(.vertical, 4)
        } header: {
            Text("AI Intelligence Overview")
        }
    }

    // MARK: - Core AI Features Section

    private var coreAIFeaturesSection: some View {
        Section {
            // Semantic Classification Toggle
            AIFeatureToggleRow(
                title: "Semantic Task Classification",
                subtitle: "Use AI to understand query intent (vs keyword matching)",
                icon: "brain.head.profile",
                iconColor: .blue,
                isOn: $useSemanticClassification,
                badge: useSemanticClassification ? "AI" : "Keywords"
            )

            // Adaptive Model Routing Toggle
            AIFeatureToggleRow(
                title: "Adaptive Model Routing",
                subtitle: "Learn optimal model selection from performance data",
                icon: "arrow.triangle.branch",
                iconColor: .orange,
                isOn: $useAdaptiveRouting,
                badge: useAdaptiveRouting ? "Learning" : "Rules"
            )

            // AI Code Analysis Toggle
            AIFeatureToggleRow(
                title: "AI Code Analysis",
                subtitle: "Semantic code understanding (vs regex patterns)",
                icon: "doc.text.magnifyingglass",
                iconColor: .green,
                isOn: $useAICodeAnalysis,
                badge: useAICodeAnalysis ? "Semantic" : "Pattern"
            )

            // Dynamic Prompts Toggle
            AIFeatureToggleRow(
                title: "Dynamic Prompt Generation",
                subtitle: "Context-aware prompts generated by AI",
                icon: "text.bubble",
                iconColor: .purple,
                isOn: $useAIDynamicPrompts,
                badge: useAIDynamicPrompts ? "Dynamic" : "Static"
            )
        } header: {
            Text("Core AI Features")
        } footer: {
            Text("AI features use more resources but provide better results through semantic understanding and continuous learning.")
        }
    }

    // MARK: - Intelligence Modes Section

    private var intelligenceModesSection: some View {
        Section {
            VStack(alignment: .leading, spacing: 12) {
                Text("Quick Presets")
                    .font(.caption)
                    .foregroundStyle(.secondary)

                HStack(spacing: 12) {
                    IntelligenceModeButton(
                        title: "Performance",
                        icon: "bolt.fill",
                        color: .orange,
                        isSelected: !useSemanticClassification && !useAICodeAnalysis
                    ) {
                        setPerformanceMode()
                    }

                    IntelligenceModeButton(
                        title: "Balanced",
                        icon: "scale.3d",
                        color: .blue,
                        isSelected: useSemanticClassification && !useAICodeAnalysis
                    ) {
                        setBalancedMode()
                    }

                    IntelligenceModeButton(
                        title: "Maximum AI",
                        icon: "sparkles",
                        color: .purple,
                        isSelected: useSemanticClassification && useAdaptiveRouting && useAICodeAnalysis && useAIDynamicPrompts
                    ) {
                        setMaximumAIMode()
                    }
                }
            }
            .padding(.vertical, 4)
        } header: {
            Text("Intelligence Mode")
        } footer: {
            Text("Performance mode uses pattern matching for speed. Maximum AI mode uses all AI features for best quality.")
        }
    }

    // MARK: - Learning Settings Section

    private var learningSettingsSection: some View {
        Section {
            Toggle("Enable Performance Learning", isOn: $enablePerformanceLearning)
                .help("Track model performance to improve future routing decisions")

            if enablePerformanceLearning {
                VStack(alignment: .leading, spacing: 4) {
                    Text("Data Retention: \(Int(learningDataRetentionDays)) days")
                        .font(.caption)
                    Slider(value: $learningDataRetentionDays, in: 7...90, step: 7)
                }

                HStack {
                    Text("Learning Records")
                    Spacer()
                    Text("\(getLearningRecordCount())")
                        .foregroundStyle(.secondary)
                }

                Button("Clear Learning Data", role: .destructive) {
                    clearLearningData()
                }
                .font(.caption)
            }
        } header: {
            Text("Learning & Adaptation")
        } footer: {
            Text("Learning data helps the AI make better model selections over time based on actual performance.")
        }
    }

    // MARK: - Performance Balance Section

    private var performanceBalanceSection: some View {
        Section {
            VStack(alignment: .leading, spacing: 8) {
                HStack {
                    Text("Cost")
                        .font(.caption)
                        .foregroundStyle(.secondary)
                    Spacer()
                    Text("Quality")
                        .font(.caption)
                        .foregroundStyle(.secondary)
                }

                Slider(value: $qualityVsCostBalance, in: 0...1)

                HStack {
                    Image(systemName: "dollarsign.circle")
                        .foregroundStyle(.green)
                    Text(balanceDescription)
                        .font(.caption)
                        .foregroundStyle(.secondary)
                    Spacer()
                    Image(systemName: "star.circle")
                        .foregroundStyle(.yellow)
                }
            }
        } header: {
            Text("Cost vs Quality Balance")
        } footer: {
            Text("Affects model selection when multiple models can handle a task. Lower values prefer cheaper models.")
        }
    }

    // MARK: - Advanced Section

    private var advancedSection: some View {
        Section {
            VStack(alignment: .leading, spacing: 4) {
                Text("Minimum AI Confidence: \(Int(minConfidenceForAI * 100))%")
                    .font(.caption)
                Slider(value: $minConfidenceForAI, in: 0.5...0.95, step: 0.05)
            }
            .help("AI classification results below this confidence will fall back to keyword matching")

            Toggle("Fallback to Keyword Matching", isOn: $fallbackToKeywordMatching)
                .help("When AI classification fails or has low confidence, use keyword-based fallback")

        } header: {
            Text("Advanced Settings")
        }
    }

    // MARK: - Actions Section

    private var actionsSection: some View {
        Section {
            Button {
                showAdvancedSettings.toggle()
            } label: {
                HStack {
                    Text(showAdvancedSettings ? "Hide Advanced Settings" : "Show Advanced Settings")
                    Spacer()
                    Image(systemName: showAdvancedSettings ? "chevron.up" : "chevron.down")
                }
            }

            Button("Reset to Defaults") {
                resetToDefaults()
            }
            .foregroundStyle(.red)
        }
    }

    // MARK: - Helper Properties

    private var activeFeatureCount: Int {
        var count = 0
        if useSemanticClassification { count += 1 }
        if useAdaptiveRouting { count += 1 }
        if useAICodeAnalysis { count += 1 }
        if useAIDynamicPrompts { count += 1 }
        return count
    }

    private var balanceDescription: String {
        if qualityVsCostBalance < 0.3 {
            return "Prioritizing cost savings"
        } else if qualityVsCostBalance < 0.7 {
            return "Balanced approach"
        } else {
            return "Prioritizing quality"
        }
    }

    // MARK: - Actions

    private func loadCurrentSettings() {
        // Load from actual AI system instances (active) and UserDefaults (excluded systems)
        Task { @MainActor in
            useSemanticClassification = TaskClassifier.shared.useSemanticClassification
            useAdaptiveRouting = ModelRouter.shared.useAdaptiveRouting
            useAICodeAnalysis = UserDefaults.standard.bool(forKey: "ai_code_analysis")
            useAIDynamicPrompts = UserDefaults.standard.bool(forKey: "ai_dynamic_prompts")
        }
    }

    private func applySemanticClassification(_ enabled: Bool) {
        Task { @MainActor in
            TaskClassifier.shared.useSemanticClassification = enabled
        }
        UserDefaults.standard.set(enabled, forKey: "ai_semantic_classification")
    }

    private func applyAdaptiveRouting(_ enabled: Bool) {
        Task { @MainActor in
            ModelRouter.shared.useAdaptiveRouting = enabled
        }
        UserDefaults.standard.set(enabled, forKey: "ai_adaptive_routing")
    }

    private func applyAICodeAnalysis(_ enabled: Bool) {
        // SwiftCodeAnalyzer is in excluded MetaAI — store preference in UserDefaults
        UserDefaults.standard.set(enabled, forKey: "ai_code_analysis")
    }

    private func applyAIDynamicPrompts(_ enabled: Bool) {
        // WorkflowTemplates is in excluded MetaAI — store preference in UserDefaults
        UserDefaults.standard.set(enabled, forKey: "ai_dynamic_prompts")
    }

    private func setPerformanceMode() {
        useSemanticClassification = false
        useAdaptiveRouting = false
        useAICodeAnalysis = false
        useAIDynamicPrompts = false
    }

    private func setBalancedMode() {
        useSemanticClassification = true
        useAdaptiveRouting = true
        useAICodeAnalysis = false
        useAIDynamicPrompts = false
    }

    private func setMaximumAIMode() {
        useSemanticClassification = true
        useAdaptiveRouting = true
        useAICodeAnalysis = true
        useAIDynamicPrompts = true
    }

    private func getLearningRecordCount() -> Int {
        // Read from UserDefaults learning storage
        if let data = UserDefaults.standard.data(forKey: "ai_intelligence_learnings") {
            do {
                let json = try JSONSerialization.jsonObject(with: data) as? [String: Any]
                if let modelPerformance = json?["modelPerformance"] as? [[String: Any]] {
                    return modelPerformance.count
                }
            } catch {
                logger.error("Failed to deserialize learning data: \(error.localizedDescription)")
            }
        }
        return 0
    }

    private func clearLearningData() {
        UserDefaults.standard.removeObject(forKey: "ai_intelligence_learnings")
    }

    private func resetToDefaults() {
        useSemanticClassification = true
        useAdaptiveRouting = true
        useAICodeAnalysis = true
        useAIDynamicPrompts = true
        enablePerformanceLearning = true
        learningDataRetentionDays = 30
        qualityVsCostBalance = 0.7
        minConfidenceForAI = 0.7
        fallbackToKeywordMatching = true
    }
}

// MARK: - Supporting Views

private struct AIFeatureToggleRow: View {
    let title: String
    let subtitle: String
    let icon: String
    let iconColor: Color
    @Binding var isOn: Bool
    let badge: String

    var body: some View {
        HStack(spacing: 12) {
            Image(systemName: icon)
                .font(.title3)
                .foregroundStyle(iconColor)
                .frame(width: 24)

            VStack(alignment: .leading, spacing: 2) {
                HStack {
                    Text(title)
                        .font(.subheadline)
                        .fontWeight(.medium)

                    Text(badge)
                        .font(.caption2)
                        .padding(.horizontal, 6)
                        .padding(.vertical, 2)
                        .background(isOn ? iconColor.opacity(0.2) : Color.gray.opacity(0.2))
                        .foregroundStyle(isOn ? iconColor : .secondary)
                        .cornerRadius(4)
                }

                Text(subtitle)
                    .font(.caption)
                    .foregroundStyle(.secondary)
            }

            Spacer()

            Toggle("", isOn: $isOn)
                .labelsHidden()
        }
        .padding(.vertical, 4)
    }
}

private struct AIFeatureStatusBadge: View {
    let title: String
    let count: Int
    let total: Int
    let color: Color

    var body: some View {
        VStack(spacing: 2) {
            Text("\(count)/\(total)")
                .font(.headline)
                .foregroundStyle(color)
            Text(title)
                .font(.caption2)
                .foregroundStyle(.secondary)
        }
        .frame(maxWidth: .infinity)
        .padding(.vertical, 8)
        .background(color.opacity(0.1))
        .cornerRadius(8)
    }
}

private struct IntelligenceModeButton: View {
    let title: String
    let icon: String
    let color: Color
    let isSelected: Bool
    let action: () -> Void

    var body: some View {
        Button(action: action) {
            VStack(spacing: 6) {
                Image(systemName: icon)
                    .font(.title2)
                Text(title)
                    .font(.caption)
            }
            .frame(maxWidth: .infinity)
            .padding(.vertical, 12)
            .background(isSelected ? color.opacity(0.2) : Color.secondary.opacity(0.1))
            .foregroundStyle(isSelected ? color : .secondary)
            .cornerRadius(8)
            .overlay(
                RoundedRectangle(cornerRadius: 8)
                    .stroke(isSelected ? color : Color.clear, lineWidth: 2)
            )
        }
        .buttonStyle(.plain)
    }
}

// MARK: - Preview

#Preview {
    AIFeaturesSettingsView()
        .frame(width: 600, height: 800)
}
