name: Setup Xcode and XcodeGen
description: Installs XcodeGen, selects Xcode version, and sets up SPM cache

inputs:
  xcode-version:
    description: Xcode version to use
    required: false
    default: '26.2'
  scheme:
    description: Scheme name (used for cache key scoping)
    required: false
    default: 'all'

runs:
  using: composite
  steps:
    - name: Select Xcode
      shell: bash
      run: sudo xcode-select -s /Applications/Xcode_${{ inputs.xcode-version }}.app/Contents/Developer

    - name: Cache XcodeGen
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: /opt/homebrew/Cellar/xcodegen
        key: ${{ runner.os }}-xcodegen-2.43.0
        restore-keys: ${{ runner.os }}-xcodegen-

    - name: Install XcodeGen
      shell: bash
      run: |
        if ! command -v xcodegen &>/dev/null; then
          brew install xcodegen
        fi
        xcodegen --version

    - name: Generate Xcode Project
      shell: bash
      run: xcodegen generate

    - name: Cache SPM packages
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: build/SourcePackages
        key: ${{ runner.os }}-${{ inputs.scheme }}-spm-${{ hashFiles('Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-${{ inputs.scheme }}-spm-
          ${{ runner.os }}-spm-
